services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  postgres:
    image: postgres:16.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fcp_mpdp_pg_poc
    networks:
      - cdp-tenant
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

  liquibase:
    image: liquibase/liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./changelog:/liquibase/changelog
    command: --url=jdbc:postgresql://postgres:5432/fcp_mpdp_pg_poc --username=postgres --password=postgres --changelog-file=changelog/db.changelog.xml update
    networks:
      - cdp-tenant

  fcp-mpdp-pg-poc:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_started
      localstack:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      POSTGRES_HOST: postgres
      POSTGRES_HOST_READ: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_GET_TOKEN_FROM_RDS: false
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
